/**
 * Sample data generator for development and testing
 * Use this to populate the database with test COWs
 */

import { COW } from "../shared/api";

export const SAMPLE_COWS: COW[] = [
  {
    id: "cow-001",
    cowId: "ACES-RYD-001",
    siteLabel: "Riyadh Main Site",
    ebuNonEbu: "EBU",
    region: "Riyadh",
    district: "Al-Olaya",
    city: "Riyadh",
    location: "King Fahd Road",
    latitude: 24.7136,
    longitude: 46.6753,
    siteStatus: "ON-AIR",
    remote: false,
    vendor: "ACES Managed Services",
    cowAge: "NEW",
    remarks: "High-capacity site serving downtown Riyadh",
    technology2g: true,
    technology3g: true,
    technologyLte: true,
    technology5g: true,
    availability2g: "Available",
    availability3g: "Available",
    availabilityLte: "Available",
    availability5g: "Available",
    configuration2g: "Standard",
    configuration3g: "Standard",
    configurationLte: "Advanced",
    configuration5g: "Advanced",
    lteBandCount: 8,
    _5gBandCount: 4,
    lteConfigurationLevel: "High",
    pgStatus: "OK",
    mdbType: "MDB-4",
    mdbStatus: "OK",
    secConnection: "Connected",
    gensetQty: 2,
    gensetMake: "Cummins",
    engine: "Diesel",
    alternator: "320KVA",
    capacity: "640KW",
    fuelTankCapacity: "5000L",
    coolingSystem: "Radiator",
    bbuStatus: "OK",
    bbuBrand: "Saft",
    voltCapacity: "48V 200Ah",
    noOfCells: 24,
    noOfStrings: 2,
    backupTime: "8 hours",
    dcPowerBrand: "Vertiv",
    totalCapacity: "48V 400Ah",
    cabinetStatus: "Good",
    rectifiersInstalled: 4,
    rectifiersRequired: 4,
    shelterOutdoor: "Shelter",
    acMake: "Daikin",
    acCapacity: "36KW",
    acType: "Split AC",
    acQty: 3,
    acStatus1: "OK",
    acStatus2: "OK",
    hvacBrand: "Daikin",
    hvacStatus: "OK",
    firePanelType: "Fike",
    firePanelStatus: "OK",
    cylinderStatus: "Full",
    manualAuto: "Auto",
    shelterTubeRodsStatus: "Good",
    securityLightStatus: "OK",
    combinationNumber: "1234-5678",
    gpsStatus: "Active",
    towerHeight: 30,
    towerType: "Self-Supporting",
    towerSystem: "Tri-Pole",
    vehicleMake: "Volvo",
    plateNumberEnglish: "RYD-5678",
    plateNumberArabic: "الرياض-5678",
    mwDish: "2.4m",
    mwFrequency: "23GHz",
    mwConfiguration: "Point-to-Point",
    mwLinkType: "Microwave",
    lastDeployDate: "2024-01-15",
    underReplacement: false,
    lastSyncedAt: new Date().toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cow-002",
    cowId: "ACES-JED-001",
    siteLabel: "Jeddah Coastal Site",
    ebuNonEbu: "NON-EBU",
    region: "Western",
    district: "Al-Balad",
    city: "Jeddah",
    location: "Red Sea Road",
    latitude: 21.5433,
    longitude: 39.1728,
    siteStatus: "ON-AIR",
    remote: true,
    vendor: "Prime Logistics",
    cowAge: "OLD",
    remarks: "Remote coastal deployment with environmental challenges",
    technology2g: true,
    technology3g: true,
    technologyLte: true,
    technology5g: false,
    availability2g: "Available",
    availability3g: "Available",
    availabilityLte: "Available",
    availability5g: "Not Available",
    configuration2g: "Basic",
    configuration3g: "Standard",
    configurationLte: "Standard",
    configuration5g: "N/A",
    lteBandCount: 4,
    _5gBandCount: 0,
    lteConfigurationLevel: "Medium",
    pgStatus: "OK",
    mdbType: "MDB-2",
    mdbStatus: "Maintenance",
    secConnection: "Connected",
    gensetQty: 1,
    gensetMake: "CAT",
    engine: "Diesel",
    alternator: "160KVA",
    capacity: "320KW",
    fuelTankCapacity: "2500L",
    coolingSystem: "Radiator",
    bbuStatus: "Warning",
    bbuBrand: "Tadiran",
    voltCapacity: "48V 100Ah",
    noOfCells: 24,
    noOfStrings: 1,
    backupTime: "4 hours",
    dcPowerBrand: "Rectifier",
    totalCapacity: "48V 100Ah",
    cabinetStatus: "Fair",
    rectifiersInstalled: 2,
    rectifiersRequired: 2,
    shelterOutdoor: "Outdoor",
    acMake: "LG",
    acCapacity: "18KW",
    acType: "Split AC",
    acQty: 2,
    acStatus1: "OK",
    acStatus2: "OK",
    hvacBrand: "LG",
    hvacStatus: "OK",
    firePanelType: "Basic",
    firePanelStatus: "OK",
    cylinderStatus: "3/4 Full",
    manualAuto: "Manual",
    shelterTubeRodsStatus: "Fair",
    securityLightStatus: "Warning",
    combinationNumber: "2345-6789",
    gpsStatus: "Active",
    towerHeight: 15,
    towerType: "Lattice",
    towerSystem: "Bi-Pole",
    vehicleMake: "Hino",
    plateNumberEnglish: "JED-1234",
    plateNumberArabic: "جدة-1234",
    mwDish: "1.8m",
    mwFrequency: "18GHz",
    mwConfiguration: "Hub-Spoke",
    mwLinkType: "Microwave",
    lastDeployDate: "2023-08-20",
    underReplacement: false,
    lastSyncedAt: new Date().toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "cow-003",
    cowId: "ACES-DMM-001",
    siteLabel: "Dammam Industrial Site",
    ebuNonEbu: "EBU",
    region: "Eastern",
    district: "Industrial",
    city: "Dammam",
    location: "Industrial Zone A",
    latitude: 26.4467,
    longitude: 50.2127,
    siteStatus: "OFF-AIR",
    remote: false,
    vendor: "ACES Managed Services",
    cowAge: "NEW",
    remarks: "Under maintenance, scheduled to return to service",
    technology2g: false,
    technology3g: false,
    technologyLte: true,
    technology5g: false,
    availability2g: "Not Available",
    availability3g: "Not Available",
    availabilityLte: "Available",
    availability5g: "Not Available",
    configuration2g: "N/A",
    configuration3g: "N/A",
    configurationLte: "Standard",
    configuration5g: "N/A",
    lteBandCount: 6,
    _5gBandCount: 0,
    lteConfigurationLevel: "High",
    pgStatus: "Down",
    mdbType: "MDB-3",
    mdbStatus: "Maintenance",
    secConnection: "Disconnected",
    gensetQty: 1,
    gensetMake: "Perkins",
    engine: "Diesel",
    alternator: "200KVA",
    capacity: "400KW",
    fuelTankCapacity: "3000L",
    coolingSystem: "Radiator",
    bbuStatus: "Critical",
    bbuBrand: "Hawker",
    voltCapacity: "48V 150Ah",
    noOfCells: 24,
    noOfStrings: 2,
    backupTime: "2 hours",
    dcPowerBrand: "Rectifier",
    totalCapacity: "48V 150Ah",
    cabinetStatus: "Poor",
    rectifiersInstalled: 2,
    rectifiersRequired: 3,
    shelterOutdoor: "Shelter",
    acMake: "Carrier",
    acCapacity: "24KW",
    acType: "Central AC",
    acQty: 2,
    acStatus1: "Down",
    acStatus2: "Down",
    hvacBrand: "Carrier",
    hvacStatus: "Down",
    firePanelType: "Advanced",
    firePanelStatus: "Off",
    cylinderStatus: "Empty",
    manualAuto: "Auto",
    shelterTubeRodsStatus: "Poor",
    securityLightStatus: "Off",
    combinationNumber: "3456-7890",
    gpsStatus: "Inactive",
    towerHeight: 25,
    towerType: "Self-Supporting",
    towerSystem: "Tri-Pole",
    vehicleMake: "Volvo",
    plateNumberEnglish: "DMM-9876",
    plateNumberArabic: "الدمام-9876",
    mwDish: "2.4m",
    mwFrequency: "23GHz",
    mwConfiguration: "Point-to-Point",
    mwLinkType: "Microwave",
    lastDeployDate: "2023-05-10",
    underReplacement: true,
    lastSyncedAt: new Date().toISOString(),
    lastUpdatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

/**
 * Seed the database with sample data
 * Only seeds if database is empty (doesn't overwrite existing data)
 *
 * NOTE: This is DISABLED in production (server/index.ts)
 * The system uses live Google Sheets synced data instead
 */
export function seedSampleData() {
  try {
    // Lazy load to avoid circular dependencies
    const { getAllCOWs, upsertCOWs } = require("./db");
    const existingCows = getAllCOWs();

    if (existingCows && existingCows.length > 0) {
      console.log(`[SEED] Database already has ${existingCows.length} COW records, skipping seed`);
      return false;
    }

    console.log("[SEED] Database is empty, seeding sample COW data...");
    upsertCOWs(SAMPLE_COWS);
    console.log(`[SEED] Successfully seeded ${SAMPLE_COWS.length} COW records`);
    return true;
  } catch (error) {
    console.error("[SEED] Error seeding data:", error);
    return false;
  }
}
