import { COW } from "../shared/api";
import { upsertCOWs, getLastSyncTime } from "./db";

const GOOGLE_SHEETS_CSV_URL =
  "https://docs.google.com/spreadsheets/d/e/2PACX-1vS0GkXnQMdKYZITuuMsAzeWDtGUqEJ3lWwqNdA67NewOsDOgqsZHKHECEEkea4nrukx4-DqxKmf62nC/pub?gid=2046046325&single=true&output=csv";

/**
 * Parse CSV text into COW records
 * Maps CSV columns to COW interface fields
 */
function parseCSVToCOWs(csvText: string): COW[] {
  const lines = csvText.trim().split("\n");
  if (lines.length < 2) return [];

  const headers = parseCSVLine(lines[0]);
  const cows: COW[] = [];

  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i]);
    if (values.length === 0) continue;

    const cow = mapRowToCOW(headers, values);
    if (cow && cow.cowId) {
      cows.push(cow);
    }
  }

  return cows;
}

/**
 * Parse a CSV line handling quoted values
 */
function parseCSVLine(line: string): string[] {
  const result: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];

    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === "," && !inQuotes) {
      result.push(current.trim());
      current = "";
    } else {
      current += char;
    }
  }
  result.push(current.trim());
  return result;
}

/**
 * Map CSV row to COW object
 * Handles column name variations and data transformation
 */
function mapRowToCOW(headers: string[], values: string[]): COW | null {
  const row: Record<string, string> = {};
  headers.forEach((header, idx) => {
    row[header.toLowerCase().trim()] = values[idx] || "";
  });

  // Required: COW ID
  if (!row["cow id"] && !row["cowid"]) return null;

  const cowId = row["cow id"] || row["cowid"];
  const now = new Date().toISOString();

  const cow: COW = {
    id: "", // Will be generated by DB
    cowId: cowId.trim(),
    siteLabel: getField(row, ["site label", "site_label", "site name"]),
    ebuNonEbu: getField(row, ["ebu / non-ebu", "ebu", "ebu_non_ebu"]),
    region: getField(row, ["region"]),
    district: getField(row, ["district"]),
    city: getField(row, ["city"]),
    location: getField(row, ["location", "location name", "site"]),
    latitude: parseFloat(getField(row, ["latitude", "lat"]) || "0") || undefined,
    longitude: parseFloat(getField(row, ["longitude", "lng"]) || "0") || undefined,
    siteStatus: (getField(row, ["site status", "status"]) || "OFF-AIR").toUpperCase() as
      | "ON-AIR"
      | "OFF-AIR"
      | "STANDBY",
    remote: getFieldBoolean(row, ["remote", "remote & metropolitan", "remote/metro"]),
    vendor: getField(row, ["vendor", "supplier"]),
    cowAge: (getField(row, ["cow old / new", "cow age", "cow_age"]).toUpperCase() || "NEW") as
      | "OLD"
      | "NEW",
    remarks: getField(row, ["remarks", "notes"]),

    // Technology
    technology2g: getFieldBoolean(row, ["2g", "2g availability"]),
    technology3g: getFieldBoolean(row, ["3g", "3g availability"]),
    technologyLte: getFieldBoolean(row, ["lte", "lte availability"]),
    technology5g: getFieldBoolean(row, ["5g", "5g availability"]),
    availability2g: getField(row, ["2g availability"]),
    availability3g: getField(row, ["3g availability"]),
    availabilityLte: getField(row, ["lte availability"]),
    availability5g: getField(row, ["5g availability"]),
    configuration2g: getField(row, ["2g configuration"]),
    configuration3g: getField(row, ["3g configuration"]),
    configurationLte: getField(row, ["lte configuration"]),
    configuration5g: getField(row, ["5g configuration"]),
    lteBandCount: parseInt(getField(row, ["lte band count"]) || "0") || undefined,
    _5gBandCount: parseInt(getField(row, ["5g band count"]) || "0") || undefined,
    lteConfigurationLevel: getField(row, ["lte configuration level"]),

    // Power & Generator
    pgStatus: getField(row, ["pg status", "power status"]),
    mdbType: getField(row, ["mdb type", "mdb"]),
    mdbStatus: getField(row, ["mdb status"]),
    secConnection: getField(row, ["sec connection", "sec"]),
    gensetQty: parseInt(getField(row, ["genset qty", "genset quantity", "genset qry"]) || "0") || 0,
    gensetMake: getField(row, ["genset make"]),
    engine: getField(row, ["engine"]),
    alternator: getField(row, ["alternator"]),
    capacity: getField(row, ["capacity"]),
    fuelTankCapacity: getField(row, ["fuel tank capacity"]),
    coolingSystem: getField(row, ["cooling system"]),
    underRepairingOvhauling: getField(row, ["under repairing", "under overhauling", "under repairing / overhauling"]),

    // BBU & DC Power
    installedBbu: getField(row, ["installed bbu", "bbu installed"]),
    bbuBrand: getField(row, ["bbu brand"]),
    voltCapacity: getField(row, ["volt & capacity", "volt capacity"]),
    noOfCells: parseInt(getField(row, ["no of cells"]) || "0") || undefined,
    noOfStrings: parseInt(getField(row, ["no of strings"]) || "0") || undefined,
    backupTime: getField(row, ["backup time"]),
    bbuStatus: getField(row, ["bbu status"]),
    dcPowerBrand: getField(row, ["dc power brand"]),
    totalCapacity: getField(row, ["total capacity"]),
    cabinetStatus: getField(row, ["cabinet status"]),
    rectifiersInstalled: parseInt(getField(row, ["rectifiers installed"]) || "0") || undefined,
    rectifiersRequired: parseInt(getField(row, ["rectifiers required"]) || "0") || undefined,

    // HVAC & Shelter
    shelterOutdoor: getField(row, ["shelter / outdoor", "shelter"]),
    acMake: getField(row, ["ac make"]),
    acCapacity: getField(row, ["ac capacity"]),
    acType: getField(row, ["ac type"]),
    acQty: parseInt(getField(row, ["ac qty", "ac quantity"]) || "0") || undefined,
    acStatus1: getField(row, ["ac status #1", "ac status 1"]),
    acStatus2: getField(row, ["ac status #2", "ac status 2"]),
    hvacBrand: getField(row, ["hvac brand"]),
    hvacStatus: getField(row, ["hvac status"]),

    // Security & Safety
    firePanelType: getField(row, ["fire panel type"]),
    firePanelStatus: getField(row, ["fire panel status"]),
    cylinderStatus: getField(row, ["cylinder status"]),
    manualAuto: getField(row, ["manual / auto", "manual auto"]),
    shelterTubeRodsStatus: getField(row, ["shelter tube rods status"]),
    securityLightStatus: getField(row, ["security light status"]),
    combinationNumber: getField(row, ["combination number"]),
    gpsStatus: getField(row, ["gps status"]),

    // Transport & Tower
    towerHeight: parseInt(getField(row, ["tower height"]) || "0") || undefined,
    towerType: getField(row, ["tower type"]),
    towerSystem: getField(row, ["tower system"]),
    vehicleMake: getField(row, ["vehicle make"]),
    plateNumberEnglish: getField(row, ["plate number english", "plate number (english)"]),
    plateNumberArabic: getField(row, ["plate number arabic", "plate number (arabic)"]),
    mwDish: getField(row, ["mw dish"]),
    mwFrequency: getField(row, ["mw frequency"]),
    mwConfiguration: getField(row, ["mw configuration"]),
    mwLinkType: getField(row, ["mw link type"]),
    lastDeployDate: getField(row, ["last deploy date", "last deploying date"]),
    underReplacement: getFieldBoolean(row, ["under replacement"]),

    // Metadata
    lastSyncedAt: now,
    lastUpdatedAt: now,
    createdAt: now,
  };

  return cow;
}

/**
 * Get field value from row with multiple possible column names
 */
function getField(row: Record<string, string>, possibleNames: string[]): string {
  for (const name of possibleNames) {
    const value = row[name.toLowerCase()];
    if (value) return value;
  }
  return "";
}

/**
 * Get boolean field value
 */
function getFieldBoolean(row: Record<string, string>, possibleNames: string[]): boolean | undefined {
  const value = getField(row, possibleNames).toLowerCase();
  if (!value) return undefined;
  return value === "yes" || value === "true" || value === "1" || value === "on";
}

/**
 * Fetch CSV from Google Sheets and sync to database
 */
export async function syncCOWsFromGoogleSheets(): Promise<{ success: boolean; count: number; error?: string }> {
  try {
    console.log("[SYNC] Starting COW data sync from Google Sheets...");
    console.log(`[SYNC] URL: ${GOOGLE_SHEETS_CSV_URL}`);

    // Fetch CSV with timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout

    const response = await fetch(GOOGLE_SHEETS_CSV_URL, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'ACES-CMMS/1.0 (COW Registry Sync Service)',
      },
    });

    clearTimeout(timeoutId);

    if (!response.ok) {
      throw new Error(`Failed to fetch Google Sheet: ${response.status} ${response.statusText}`);
    }

    const csvText = await response.text();
    console.log(`[SYNC] Downloaded CSV (${csvText.length} bytes)`);

    if (!csvText || csvText.length < 10) {
      throw new Error("CSV is empty or too small");
    }

    // Parse CSV to COWs
    const cows = parseCSVToCOWs(csvText);

    if (cows.length === 0) {
      console.warn("[SYNC] No valid COW records found in CSV. Check column headers and data format.");
      return { success: false, count: 0, error: "No valid COW records found in CSV" };
    }

    console.log(`[SYNC] Parsed ${cows.length} COW records`);

    // Upsert into database
    upsertCOWs(cows);
    console.log(`[SYNC] Successfully synced ${cows.length} COW records`);

    return { success: true, count: cows.length };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error(`[SYNC] Error during sync: ${errorMessage}`);

    // Log more context for debugging
    if (errorMessage.includes("ERR_ABORTED")) {
      console.error("[SYNC] Request timed out - Google Sheets URL may be unreachable");
    } else if (errorMessage.includes("401") || errorMessage.includes("403")) {
      console.error("[SYNC] Access denied - Google Sheets may require authentication or be private");
    } else if (errorMessage.includes("404")) {
      console.error("[SYNC] Sheet not found - check the Google Sheets URL");
    }

    return { success: false, count: 0, error: errorMessage };
  }
}

/**
 * Start periodic sync (every 15-30 minutes as recommended)
 */
export function startPeriodicSync(intervalMinutes: number = 15) {
  console.log(`[SYNC] Starting periodic sync every ${intervalMinutes} minutes`);

  // Run once on startup
  syncCOWsFromGoogleSheets().catch((err) => {
    console.error("[SYNC] Initial sync failed:", err);
  });

  // Then run periodically
  setInterval(
    () => {
      syncCOWsFromGoogleSheets().catch((err) => {
        console.error("[SYNC] Periodic sync failed:", err);
      });
    },
    intervalMinutes * 60 * 1000
  );
}
